### ISSUE TITLE
New release with fix commit?

### ISSUE THREAD

**Issue by totycro** [satodoc/httpie-oauth2-client-credentials#3]
Hi,

I've just installed via pip and noticed that it's not working because this fix isn't included in the version that is published on pypi:
https://github.com/satodoc/httpie-oauth2-client-credentials/commit/a2c662a8c66050aa7f1e11675bcdecf6479860c6

Could you make a release and publish to pypi?

**Comment by satodoc** [comment]
Sorry for the delay, but we have released it as [v0.1.2](https://pypi.org/project/httpie-oauth2-client-credentials/)
